# Generated by Django 3.2.9 on 2021-12-01 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal_assets', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personal_assets',
            name='category',
            field=models.CharField(choices=[('savings', 'savings'), ('stocks', 'stocks'), ('crypto', 'crypto'), ('other', 'other')], max_length=20),
        ),
    ]
