# Generated by Django 3.2.9 on 2021-12-07 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal_income', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personal_income',
            name='category',
            field=models.CharField(choices=[('Paycheck', 'Paycheck'), ('Selling', 'Selling'), ('Passive', 'Passive'), ('Misc', 'Misc')], max_length=10),
        ),
    ]
