# Generated by Django 3.2.9 on 2021-12-01 12:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('household', '0001_initial'),
        ('auth_jwt', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='household',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='household.household'),
        ),
    ]
