# Generated by Django 3.2.9 on 2021-12-08 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('personal_assets', '0002_alter_personal_assets_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personal_assets',
            name='category',
        ),
        migrations.RemoveField(
            model_name='personal_assets',
            name='share',
        ),
    ]
