# Generated by Django 3.2.9 on 2021-12-08 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal_assets', '0003_auto_20211208_1447'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personal_assets',
            name='amount',
            field=models.IntegerField(),
        ),
    ]
