# Generated by Django 3.2.9 on 2021-12-02 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('household_expenses', '0003_household_expenses_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='household_expenses',
            old_name='user',
            new_name='creator',
        ),
    ]
